### PR TITLE
Adding renewed support for PBS

### PR DESCRIPTION
**Pull request by PerilousApricot**
The "pbsv2" scheduler talks with pbs via the command line tools, which
negates the need to have libtorque + python binaries installed.

(hold off just a second while I wait on my test jobs to come back. I've been using this for two
years, but I'm not 100% that I merged ALL of the needed changes)

### CODE REVIEW

**Comment by belforte** [comment]
May I leave this for after dust settled on DBS2/3 migration ?

**Comment by belforte** [comment]
Do not forget to make a new ProdCommon as welll, see
https://github.com/dmwm/ProdCommon/pull/3
https://github.com/dmwm/ProdCommon/pull/2

**Comment by PerilousApricot** [comment]
Of course, feel free to hold off on it, stefano. I know you're busy.

**Comment by belforte** [comment]
the new ProdCommon tag is
PRODCOMMON_0_12_18_CRAB_59

**Comment by belforte** [comment]
no way this can harm

**Comment by belforte** [comment]
@PerilousApricot There's a CRAB_2_10_2_patch4 with this in (among other small things). Feel free to try.
http://cmsdoc.cern.ch/cms/ccs/wm/www/Crab/Docs/CRAB_new.tgz

**Pull request merged**
